export const products = [
    {
      id: 1,
      name: 'Apples',
      description: 'Fresh and juicy apples, perfect for snacking or baking.',
      price: 1.99,
      expirationDate: '2023-09-30',
      category: 'Fruits',
    },
    {
      id: 2,
      name: 'Bananas',
      description: 'Ripe and ready-to-eat bananas, a great source of potassium.',
      price: 0.99,
      expirationDate: '2023-09-25',
      category: 'Fruits',
    },
    {
      id: 3,
      name: 'Carrots',
      description: 'Crisp and orange carrots, ideal for salads or as a healthy snack.',
      price: 2.49,
      expirationDate: '2023-09-30',
      category: 'Vegetables',
    },
    {
      id: 4,
      name: 'Spinach',
      description: 'Nutrient-rich spinach, perfect for salads, smoothies, or sautéing.',
      price: 2.99,
      expirationDate: '2023-09-28',
      category: 'Vegetables',
    },
    {
      id: 5,
      name: 'Milk',
      description: 'Fresh dairy milk, essential for your daily calcium intake.',
      price: 3.49,
      expirationDate: '2023-09-23',
      category: 'Dairy',
    },
    {
      id: 6,
      name: 'Bread',
      description: 'Soft and freshly baked bread, great for sandwiches or toasting.',
      price: 2.79,
      expirationDate: '2023-09-25',
      category: 'Bakery',
    },
    {
      id: 7,
      name: 'Eggs',
      description: 'Grade A large eggs, perfect for breakfast or baking.',
      price: 2.99,
      expirationDate: '2023-09-30',
      category: 'Dairy',
    },
    {
      id: 8,
      name: 'Rice',
      description: 'High-quality rice, great for various culinary dishes.',
      price: 4.99,
      expirationDate: '2024-01-31',
      category: 'Grains',
    },
    {
      id: 9,
      name: 'Chicken Breasts',
      description: 'Boneless chicken breasts, perfect for grilling or roasting.',
      price: 6.99,
      expirationDate: '2023-09-27',
      category: 'Meat',
    },
    {
      id: 10,
      name: 'Tomatoes',
      description: 'Fresh tomatoes, great for salads, sandwiches, or sauces.',
      price: 1.49,
      expirationDate: '2023-09-29',
      category: 'Vegetables',
    },
    // Add more grocery items and descriptions as needed
  ];
  